// CRITICAL
export const CONTROLLER_EVENT_TYPES = [
  "status",
  "gpu",
  "metrics",
  "launch_progress",
  "download_progress",
  "download_state",
  "temporal_status",
  "chat_session_created",
  "chat_session_updated",
  "chat_session_deleted",
  "chat_session_forked",
  "chat_session_compacted",
  "chat_message_upserted",
  "chat_usage_updated",
  "agent_files_listed",
  "agent_file_read",
  "agent_file_written",
  "agent_file_deleted",
  "agent_directory_created",
  "agent_file_moved",
  "agent_plan_updated",
  "recipe_created",
  "recipe_updated",
  "recipe_deleted",
  "mcp_server_created",
  "mcp_server_updated",
  "mcp_server_deleted",
  "mcp_server_enabled",
  "mcp_server_disabled",
  "mcp_tool_called",
  "runtime_vllm_upgraded",
] as const;

