// CRITICAL
import type { LlamacppOption } from "./types";

export const LLAMACPP_OPTIONS_PART_1A: LlamacppOption[] = [
  {
    key: "model-url",
    label: "Model URL",
    type: "text",
    tab: "model",
    placeholder: "https://.../model.gguf",
  },
  {
    key: "hf-repo",
    label: "HF Repo",
    type: "text",
    tab: "model",
    placeholder: "org/model",
  },
  {
    key: "hf-file",
    label: "HF File",
    type: "text",
    tab: "model",
    placeholder: "model.gguf",
  },
  {
    key: "hf-token",
    label: "HF Token",
    type: "text",
    tab: "model",
    placeholder: "hf_...",
  },
  {
    key: "hf-cache",
    label: "HF Cache Dir",
    type: "text",
    tab: "model",
    placeholder: "/models/cache",
  },
  {
    key: "lora",
    label: "LoRA",
    type: "text",
    tab: "model",
    placeholder: "/path/to/lora.gguf",
  },
  {
    key: "lora-scaled",
    label: "LoRA (Scaled)",
    type: "text",
    tab: "model",
    placeholder: "/path/to/lora.gguf,scale",
  },
  {
    key: "control-vector",
    label: "Control Vector",
    type: "text",
    tab: "model",
    placeholder: "/path/to/control-vector.bin",
  },
  {
    key: "control-vector-scaled",
    label: "Control Vector (Scaled)",
    type: "text",
    tab: "model",
    placeholder: "/path/to/control-vector.bin,scale",
  },
  {
    key: "control-vector-layer-range",
    label: "Control Vector Layers",
    type: "text",
    tab: "model",
    placeholder: "start,end",
  },
  {
    key: "chat-template",
    label: "Chat Template",
    type: "text",
    tab: "model",
  },
  {
    key: "chat-template-file",
    label: "Chat Template File",
    type: "text",
    tab: "model",
  },
  {
    key: "system-prompt",
    label: "System Prompt",
    type: "text",
    tab: "model",
  },
  {
    key: "prompt",
    label: "Prompt",
    type: "text",
    tab: "model",
  },
  {
    key: "prompt-file",
    label: "Prompt File",
    type: "text",
    tab: "model",
  },
  {
    key: "grammar",
    label: "Grammar",
    type: "text",
    tab: "model",
  },
  {
    key: "grammar-file",
    label: "Grammar File",
    type: "text",
    tab: "model",
  },
  {
    key: "ctx-size",
    label: "Context Size Override",
    type: "number",
    tab: "model",
    placeholder: "8192",
  },
  {
    key: "rope-scaling",
    label: "RoPE Scaling",
    type: "select",
    tab: "model",
    options: ["none", "linear", "yarn"],
  },
  {
    key: "rope-scale",
    label: "RoPE Scale",
    type: "number",
    tab: "model",
  },
  {
    key: "rope-freq-base",
    label: "RoPE Freq Base",
    type: "number",
    tab: "model",
  },
  {
    key: "rope-freq-scale",
    label: "RoPE Freq Scale",
    type: "number",
    tab: "model",
  },
  {
    key: "yarn-orig-ctx",
    label: "YaRN Orig Ctx",
    type: "number",
    tab: "model",
  },
  {
    key: "yarn-ext-factor",
    label: "YaRN Ext Factor",
    type: "number",
    tab: "model",
  },
  {
    key: "yarn-attn-factor",
    label: "YaRN Attn Factor",
    type: "number",
    tab: "model",
  },
  {
    key: "yarn-beta-fast",
    label: "YaRN Beta Fast",
    type: "number",
    tab: "model",
  },
  {
    key: "yarn-beta-slow",
    label: "YaRN Beta Slow",
    type: "number",
    tab: "model",
  },
];

