// CRITICAL
import type { LlamacppOption } from "./types";

export const LLAMACPP_OPTIONS_PART_2: LlamacppOption[] = [
  {
    key: "threads",
    label: "Threads",
    type: "number",
    tab: "performance",
  },
  {
    key: "threads-batch",
    label: "Threads (Batch)",
    type: "number",
    tab: "performance",
  },
  {
    key: "threads-http",
    label: "Threads (HTTP)",
    type: "number",
    tab: "performance",
  },
  {
    key: "batch-size",
    label: "Batch Size",
    type: "number",
    tab: "performance",
  },
  {
    key: "ubatch-size",
    label: "Micro Batch Size",
    type: "number",
    tab: "performance",
  },
  {
    key: "parallel",
    label: "Parallel Slots",
    type: "number",
    tab: "performance",
  },
  {
    key: "cpu-mask",
    label: "CPU Mask",
    type: "text",
    tab: "performance",
  },
  {
    key: "cpu-range",
    label: "CPU Range",
    type: "text",
    tab: "performance",
  },
  {
    key: "prio",
    label: "CPU Priority",
    type: "number",
    tab: "performance",
  },
  {
    key: "poll",
    label: "Poll",
    type: "number",
    tab: "performance",
  },
  {
    key: "poll-batch",
    label: "Poll Batch",
    type: "number",
    tab: "performance",
  },
  {
    key: "samplers",
    label: "Samplers",
    type: "text",
    tab: "features",
    placeholder: "top-k;top-p;min-p;temp",
  },
  {
    key: "temp",
    label: "Temperature",
    type: "number",
    tab: "features",
  },
  {
    key: "top-k",
    label: "Top K",
    type: "number",
    tab: "features",
  },
  {
    key: "top-p",
    label: "Top P",
    type: "number",
    tab: "features",
  },
  {
    key: "min-p",
    label: "Min P",
    type: "number",
    tab: "features",
  },
  {
    key: "typical",
    label: "Typical P",
    type: "number",
    tab: "features",
  },
  {
    key: "repeat-last-n",
    label: "Repeat Last N",
    type: "number",
    tab: "features",
  },
  {
    key: "repeat-penalty",
    label: "Repeat Penalty",
    type: "number",
    tab: "features",
  },
  {
    key: "presence-penalty",
    label: "Presence Penalty",
    type: "number",
    tab: "features",
  },
  {
    key: "frequency-penalty",
    label: "Frequency Penalty",
    type: "number",
    tab: "features",
  },
  {
    key: "mirostat",
    label: "Mirostat",
    type: "number",
    tab: "features",
  },
  {
    key: "mirostat-lr",
    label: "Mirostat LR",
    type: "number",
    tab: "features",
  },
  {
    key: "mirostat-ent",
    label: "Mirostat Entropy",
    type: "number",
    tab: "features",
  },
  {
    key: "ignore-eos",
    label: "Ignore EOS",
    type: "boolean",
    tab: "features",
  },
  {
    key: "logit-bias",
    label: "Logit Bias",
    type: "text",
    tab: "features",
    placeholder: "token=weight,token=weight",
  },
  {
    key: "n-predict",
    label: "Max Tokens",
    type: "number",
    tab: "features",
  },
  {
    key: "n-keep",
    label: "Tokens to Keep",
    type: "number",
    tab: "features",
  },
  {
    key: "api-key",
    label: "API Key",
    type: "text",
    tab: "features",
  },
];

